export const VERIFICATION_RESEND_COOLDOWN_SECONDS = 60
export const APP_NAME = 'SDMastery'
export const DEFAULT_API_BASE_URL = 'http://localhost:8000/api/v1'
export const ROADMAP_CORE_TOPICS_TOTAL = 26
export const ROADMAP_ADVANCED_TOPICS_TOTAL = 27
export const ROADMAP_TOTAL_TOPICS = ROADMAP_CORE_TOPICS_TOTAL + ROADMAP_ADVANCED_TOPICS_TOTAL
export const TOPICS_QUERY_STALE_TIME_MS = 5 * 60 * 1000
